kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  shm_size: 256m
  commands:
  - echo hello
  - echo world
  - df -h | grep shm

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde
